version: '3.9'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personapi
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DBURL: jdbc:postgresql://db:5432/personapi
      DBUSERNAME: example_user
      SPRING_DATASOURCE_PASSWORD: example_password
